services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
      target: ollama-base
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  openwebui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - openwebui_data:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  ollama_models:
  openwebui_data:
