services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  openwebui:
    build:
      context: .
      dockerfile: Dockerfile.openwebui
    container_name: openwebui
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
    volumes:
      - openwebui_data:/app/backend/data
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  ollama_data:
  openwebui_data:
